export CMDSTAN_OLD=$CMDSTAN
export CMDSTAN=/opt/conda/conda-bld/cmdstan_1665741995730/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/cmdstan
export CMDSTAN=/opt/conda/conda-bld/cmdstan_1665742701770/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/cmdstan
